# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_parser_pb2 as message__parser__pb2


class MessageParserStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
                '/pb.MessageParser/Parse',
                request_serializer=message__parser__pb2.ParserRequest.SerializeToString,
                response_deserializer=message__parser__pb2.ParserResponse.FromString,
                )


class MessageParserServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Parse(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=message__parser__pb2.ParserRequest.FromString,
                    response_serializer=message__parser__pb2.ParserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.MessageParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageParser(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.MessageParser/Parse',
            message__parser__pb2.ParserRequest.SerializeToString,
            message__parser__pb2.ParserResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
