# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_parser.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_parser.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z;github.com/redhat-cne/cloud-event-proxy/plugins/hw_event/pb',
  serialized_pb=b'\n\x14message_parser.proto\x12\x02pb\"9\n\rParserRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x14\n\x0cmessage_args\x18\x02 \x03(\t\"G\n\x0eParserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x12\n\nresolution\x18\x03 \x01(\t2A\n\rMessageParser\x12\x30\n\x05Parse\x12\x11.pb.ParserRequest\x1a\x12.pb.ParserResponse\"\x00\x42=Z;github.com/redhat-cne/cloud-event-proxy/plugins/hw_event/pbb\x06proto3'
)




_PARSERREQUEST = _descriptor.Descriptor(
  name='ParserRequest',
  full_name='pb.ParserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='pb.ParserRequest.message_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_args', full_name='pb.ParserRequest.message_args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=85,
)


_PARSERRESPONSE = _descriptor.Descriptor(
  name='ParserResponse',
  full_name='pb.ParserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pb.ParserResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='severity', full_name='pb.ParserResponse.severity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='pb.ParserResponse.resolution', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['ParserRequest'] = _PARSERREQUEST
DESCRIPTOR.message_types_by_name['ParserResponse'] = _PARSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParserRequest = _reflection.GeneratedProtocolMessageType('ParserRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSERREQUEST,
  '__module__' : 'message_parser_pb2'
  # @@protoc_insertion_point(class_scope:pb.ParserRequest)
  })
_sym_db.RegisterMessage(ParserRequest)

ParserResponse = _reflection.GeneratedProtocolMessageType('ParserResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARSERRESPONSE,
  '__module__' : 'message_parser_pb2'
  # @@protoc_insertion_point(class_scope:pb.ParserResponse)
  })
_sym_db.RegisterMessage(ParserResponse)


DESCRIPTOR._options = None

_MESSAGEPARSER = _descriptor.ServiceDescriptor(
  name='MessageParser',
  full_name='pb.MessageParser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=160,
  serialized_end=225,
  methods=[
  _descriptor.MethodDescriptor(
    name='Parse',
    full_name='pb.MessageParser.Parse',
    index=0,
    containing_service=None,
    input_type=_PARSERREQUEST,
    output_type=_PARSERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEPARSER)

DESCRIPTOR.services_by_name['MessageParser'] = _MESSAGEPARSER

# @@protoc_insertion_point(module_scope)
